name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push client
        uses: docker/build-push-action@v5
        with:
          context: src/client
          platforms: macOS/amd64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/komponent-client:latest
      -
        name: Build and push server
        uses: docker/build-push-action@v5
        with:
          context: src/server
          platforms: macOS/amd64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/komponent-server:latest